services:
  ansible:
    build: .
    container_name: ansible
    image: ansible
    volumes:
      - .:/ansibleScripts
      - ~/.ssh/config:/root/.ssh/config
    working_dir: /ansibleScripts
    entrypoint: ["/bin/sh", "-c"]
    command: ["tail -f /dev/null"]