
- name: Provision juniperRouter
  hosts: juniperRouter
  connection: local
  roles:
    - juniperSRXs

# - name: Provision ciscoRouter
#   hosts: ciscoRouter
#   connection: local
#   gather_facts: no
#   roles:
#     - cisco800


