
# - name: Create exports directory
#   ansible.builtin.file:
#     path: /exports
#     state: directory
#     mode: '0755
# I dont think this to be neccesary


- name: Installing nfs-kernel-server
  ansible.builtin.apt:
    name: nfs-kernel-server
    update_cache: true