
- name: "Do Config Backup"
  ansible.builtin.include_tasks: ../../cisco/tasks/getCurrentConfig.yml


- block:


  - name: Creation of VLANs and Rapid PVST+
    ansible.builtin.include_tasks: createVlansAndSTP.yml
    vars:
      vlans:
        - num: 5
          name: Management
          stpBridgePriority: 4096

        - num: 10
          name: Internal_Services_Network
          stpBridgePriority: 28672

        - num: 50
          name: External_Services_Network
          stpBridgePriority: 28672


  - name: Configure Interfaces without downlink
    ansible.builtin.include_tasks: setInterfaceStatus.yml
    vars:
      interfaces:
        - name: "Fa0/1"
          active: False
        - name: "Fa0/2"
          active: False
        - name: "Fa0/3"
          active: False
        - name: "Fa0/4"
          active: False

        - name: "Fa0/5"
          mode: "access"
          nativeVlan: 10


        - name: "Fa0/6"
          mode: "access"
          nativeVlan: 50

        - name: "Fa0/7"
          mode: "trunk"
          nativeVlan: 5
          vlans: "5,10,50"

        - name: "Fa0/8"
          mode: "trunk"
          nativeVlan: 5
          vlans: "5,10,50"  
          
        - name: "Gi0/1"
          active: False

  - name: "Set the default-gateway to the VRRP Virtual IP of the routers"
    ansible.builtin.include_tasks: setSwitchDefGateway.yml

  - name: "Change password of User to the strongest one"
    ansible.builtin.include_tasks: ../../cisco/tasks/setUserAndPassword.yml

  - name: "Show spanning tree related information"
    ansible.builtin.include_tasks: showSpanningTree.yml

  rescue:
    - name: "Do Rollback"
      ansible.builtin.include_tasks: ../../cisco/tasks/rollbackConfig.yml






- name: Reset connection to ensure clean slate for next device
  meta: reset_connection