- name: Add new User and Uniformise Passwords
  ios_config:
      lines:
        - username {{ newUser }} privilege {{ newUserPrivilege | default(15) }} secret {{ numberPasswordStrong }}
        - enable secret {{ numberPasswordStrong }}
      save_when: changed