
- juniper.device.config:
    lines: 
      - set routing-options static route 0.0.0.0/0 next-hop 10.2.1.3 metric {{ staticDefGateMetric | default(190) }} 
    load: set
    format: set
    commit: true
    timeout: 180
  register: response

- name: Print the complete response.
  ansible.builtin.debug:
    var: response