- name: "Do Config Backup"
  ansible.builtin.include_tasks: getCurrentConfig.yml


- name: Add Vlans to Trunk
  juniper.device.junos_config:
    src: addVlansToTrunk.j2
    format: text # Ensure configuration is applied as text commands
  notify: Retrieve diffs

