
- ansible.builtin.set_fact:
    backupPath: "roles/juniperSRXs/files/backups/{{ inventory_hostname }}_configBackup.cfg"
  run_once: true



- name: Rollback configuration
  juniper.device.config:
    load: update
    src: "{{ backupPath }}"
    format: text
    commit: true
    timeout: 180


- name: Report Rollback
  ansible.builtin.debug:
    msg: "Configuration successfully rollbacked using: {{ backupPath }}"
