
- juniper.device.config:
    lines: 
      - set system login user {{ newUser }} class super-user
      - set system login user {{ newUser }} authentication plain-text-password {{ numberPasswordStrong }}
    load: set
    format: set
    commit: true
    timeout: 180
  no_log: True
  register: response



- name: Print the complete response.
  ansible.builtin.debug:
    var: response