


- name: Configure User {{ newUser }} with Encrypted Password
  juniper.device.junos_user:
    name: "{{ newUser }}"
    role: super-user
    encrypted_password: "{{ numberPasswordStrong | password_hash('sha512') }}"
    state: present
  register: response


- name: Print the complete response
  ansible.builtin.debug:
    var: response