- name: Configure User with Encrypted Password
  juniper.device.config:
    load: "set"
    format: "set"
    commit: True
    lines: 
      - "set system login user {{ newUser }} class super-user"
      - "set system login user {{ newUser }} authentication encrypted-password {{ numberPasswordStrong | password_hash('sha512') }}"
  register: response


- name: Print the complete response
  ansible.builtin.debug:
    var: response