

interfacesToConfigure:

  - index: 0
    disable: True

  - index: 1
    disable: True

  - index: 2
    disable: True

  - index: 3
    disable: True

  - index: 4
    disable: True

  - index: 5
    disable: True

  - index: 6
    disable: True

  - index: 7
    unit: 0
    ipAddress: 10.2.1.1
    mask: 29


interfacesVlanToConfigure:
  - index: 0
    vlanNum: 5
    ipAddress: 10.5.5.2
    mask: 28
    name: "Management"
    isManagement: True


  - index: 1
    vlanNum: 10
    ipAddress: 10.10.10.1
    mask: 28
    name: "Internal_Network_Services"



vlanToInterfaceMappings:

  - interface: ge-0/0/0
    vlans: 
      - vlanNum: 5
        isNative: True

      - vlanNum: 10




networksToAdvertiseOSPF:

- index: 0
  intName: ge-0/0/7
  isPointToPoint: True

- index: 1
  intName: vlan.5
  passive: True

- index: 2
  intName: vlan.10
  passive: True

ospfRouterId: 2.2.2.2