linesInEtcExports:

  - line: "/exports/miguel 10.7.7.74/32(rw,sync,no_subtree_check,no_root_squash)"
  - line: "/exports/backups 10.7.7.74/32(rw,sync,no_subtree_check,no_root_squash)"
  - line: "/exports/logs 10.7.7.74/32(rw,sync,no_subtree_check,no_root_squash)"

  - line: "/exports/miguel 10.2.1.4/32(rw,sync,no_subtree_check,no_root_squash)"
  - line: "/exports/backups 10.2.1.4/32(rw,sync,no_subtree_check,no_root_squash)"
  - line: "/exports/logs 10.2.1.4/32(rw,sync,no_subtree_check,no_root_squash)"


subdirectoriesExports:
  - subdirectory: "miguel"
  - subdirectory: "backups"
  - subdirectory: "logs"